name: cannabis-epigenome-paper1
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - bedtools
  - bowtie2=2.5.4
  - samtools=1.22.1
  - star=2.7.11b
  - subread=2.0.6
  - bismark
  - repeatmasker
  - repeatmodeler
